SELECT H.*, C.*
FROM HOADON H
JOIN CHITIETHOADON C ON H.MAHOADON = C.MAHOADON
ORDER BY H.NGAYLAPHD DESC;

select * from HOADON where MAHOADON = 'HD09'
SELECT * FROM KHACHHANG
SELECT * FROM KHACHHANG WHERE TENKH LIKE '%K%' AND DIACHI LIKE '%H%' AND SDT LIKE '%03%'