SELECT 
  
    KHACHHANG.MAKH,
    KHACHHANG.TENKH,
    HOADON.MAHOADON AS MAHD,
    HOADON.NGAYLAPHD AS NGAYLAPHD,
    CHITIETHOADON.SOLUONGMUA,
    CHITIETHOADON.MASACH,
    SACH.TENSACH,
	  KHACHHANG.DIACHI,
    SACH.GIAMUA
FROM 
    KHACHHANG
JOIN 
    HOADON ON KHACHHANG.MAKH = HOADON.MAKH
JOIN 
    CHITIETHOADON ON HOADON.MAHOADON = CHITIETHOADON.MAHOADON
JOIN 
    SACH ON CHITIETHOADON.MASACH = SACH.MASACH
ORDER BY 
    HOADON.NGAYLAPHD DESC;


